# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

# [languages]
#   [languages.en]
[[languages.en.menu.main]]
  name = "Home"
  url = "#about"
  weight = 10

[[languages.en.menu.main]]
  name = "Skills"
  url = "#skills"
  weight = 20

[[languages.en.menu.main]]
  name = "Projects"
  url = "#projects"
  weight = 30

[[languages.en.menu.main]]
  name = "Experience"
  url = "#experience"
  weight = 40

[[languages.en.menu.main]]
  name = "Contact"
  url = "#contact"
  weight = 60
# [languages.zh-Hant]
[[languages.zh-Hant.menu.main]]
  name = "主頁"
  url = "#about"
  weight = 10

[[languages.zh-Hant.menu.main]]
  name = "技能專長"
  url = "#skills"
  weight = 20

[[languages.zh-Hant.menu.main]]
  name = "作品"
  url = "#projects"
  weight = 30

[[languages.zh-Hant.menu.main]]
  name = "經歷"
  url = "#experience"
  weight = 40

[[languages.zh-Hant.menu.main]]
  name = "聯絡資訊"
  url = "#contact"
  weight = 60

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 70
